wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    code_path: code/src/train.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/rmse
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/rmse
      5: 1
      6:
      - 1
    - 1: val/rmse_best
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    - 1: test/rmse
      5: 1
      6:
      - 1
    python_version: 3.10.8
    start_time: 1673640522.259755
    t:
      1:
      - 1
      - 5
      - 9
      - 35
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 35
      - 50
      - 53
      - 55
      3:
      - 2
      - 7
      - 15
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 5
callbacks/early_stopping/_target_:
  desc: null
  value: pytorch_lightning.callbacks.EarlyStopping
callbacks/early_stopping/check_finite:
  desc: null
  value: true
callbacks/early_stopping/check_on_train_epoch_end:
  desc: null
  value: null
callbacks/early_stopping/divergence_threshold:
  desc: null
  value: null
callbacks/early_stopping/min_delta:
  desc: null
  value: 0.5
callbacks/early_stopping/mode:
  desc: null
  value: min
callbacks/early_stopping/monitor:
  desc: null
  value: val/rmse_best
callbacks/early_stopping/patience:
  desc: null
  value: 3
callbacks/early_stopping/stopping_threshold:
  desc: null
  value: null
callbacks/early_stopping/strict:
  desc: null
  value: true
callbacks/early_stopping/verbose:
  desc: null
  value: false
callbacks/model_checkpoint/_target_:
  desc: null
  value: pytorch_lightning.callbacks.ModelCheckpoint
callbacks/model_checkpoint/auto_insert_metric_name:
  desc: null
  value: false
callbacks/model_checkpoint/dirpath:
  desc: null
  value: /home/o-ozoglu/cmapss/logs/train/multiruns/2023-01-13_19-58-55/9/checkpoints
callbacks/model_checkpoint/every_n_epochs:
  desc: null
  value: null
callbacks/model_checkpoint/every_n_train_steps:
  desc: null
  value: null
callbacks/model_checkpoint/filename:
  desc: null
  value: epoch_{epoch:03d}
callbacks/model_checkpoint/mode:
  desc: null
  value: min
callbacks/model_checkpoint/monitor:
  desc: null
  value: val/rmse
callbacks/model_checkpoint/save_last:
  desc: null
  value: true
callbacks/model_checkpoint/save_on_train_epoch_end:
  desc: null
  value: null
callbacks/model_checkpoint/save_top_k:
  desc: null
  value: 1
callbacks/model_checkpoint/save_weights_only:
  desc: null
  value: false
callbacks/model_checkpoint/train_time_interval:
  desc: null
  value: null
callbacks/model_checkpoint/verbose:
  desc: null
  value: false
callbacks/model_summary/_target_:
  desc: null
  value: pytorch_lightning.callbacks.RichModelSummary
callbacks/model_summary/max_depth:
  desc: null
  value: 0
ckpt_path:
  desc: null
  value: null
datamodule/_target_:
  desc: null
  value: src.datamodules.cmapss.CMAPSSDataModule
datamodule/batch_size:
  desc: null
  value: 32
datamodule/data_dir:
  desc: null
  value: /home/o-ozoglu/cmapss/data/
datamodule/fd:
  desc: null
  value: 1
extras/enforce_tags:
  desc: null
  value: true
extras/ignore_warnings:
  desc: null
  value: true
extras/print_config:
  desc: null
  value: false
model/_target_:
  desc: null
  value: src.modules.pl_module.PLModule
model/net/_target_:
  desc: null
  value: src.models.exp.CNNLSTMTransformer
model/net/dim_feedforward:
  desc: null
  value: 512
model/net/lstm_hidden:
  desc: null
  value: 32
model/net/nhead:
  desc: null
  value: 2
model/net/num_encoder_layers:
  desc: null
  value: 2
model/net/num_lstm_layers:
  desc: null
  value: 2
model/optimizer/_partial_:
  desc: null
  value: true
model/optimizer/_target_:
  desc: null
  value: torch.optim.Adam
model/optimizer/lr:
  desc: null
  value: 0.004396893641976712
model/optimizer/weight_decay:
  desc: null
  value: 0.03288064461501717
model/params/non_trainable:
  desc: null
  value: 0
model/params/total:
  desc: null
  value: 137437
model/params/trainable:
  desc: null
  value: 137437
model/scheduler/_partial_:
  desc: null
  value: true
model/scheduler/_target_:
  desc: null
  value: torch.optim.lr_scheduler.ReduceLROnPlateau
model/scheduler/factor:
  desc: null
  value: 0.1
model/scheduler/mode:
  desc: null
  value: min
model/scheduler/patience:
  desc: null
  value: 10
seed:
  desc: null
  value: 42
tags:
  desc: null
  value:
  - optuna_sweep
task_name:
  desc: null
  value: train
trainer/_target_:
  desc: null
  value: pytorch_lightning.Trainer
trainer/accelerator:
  desc: null
  value: gpu
trainer/check_val_every_n_epoch:
  desc: null
  value: 1
trainer/default_root_dir:
  desc: null
  value: /home/o-ozoglu/cmapss/logs/train/multiruns/2023-01-13_19-58-55/9
trainer/deterministic:
  desc: null
  value: true
trainer/devices:
  desc: null
  value: 1
trainer/max_epochs:
  desc: null
  value: 10
trainer/min_epochs:
  desc: null
  value: 1
